services:
  db:
    image: postgres
    ports:
      - '${DOCKER_DB_PORT}:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  redis:
    image: redis:7.2.2-alpine
    ports:
      - "${DOCKER_REDIS_PORT}:6379"
    volumes:
      - ./redis_data/data:/var/lib/redis/data

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_HOST=
      - DB_PORT=5432
      - DB_NAME=hanghae-test
      - DB_USERNAME=postgres
      - DB_PASSWORD=1234
    depends_on:
      - db
      - memory
    ports:
      - '${DOCKER_APP_PORT}:3000'
    volumes:
      - ./:/app/

volumes:
  db_data:
