name: push-ci

on: [push]

jobs:
  app_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - if: ${{ startsWith(github.ref, 'refs/heads') && !startsWith(github.ref, 'refs/heads/main') }}
        run: |
          pnpm install --frozen-lockfile
          NODE_ENV=development pnpm test

      - if: ${{ startsWith(github.ref, 'refs/heads/main') }}
        run: |
          pnpm install --frozen-lockfile
          NODE_ENV=production pnpm test

  app_itg_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - if: ${{ startsWith(github.ref, 'refs/heads') && !startsWith(github.ref, 'refs/heads/main') }}
        run: |
          pnpm install --frozen-lockfile
          NODE_ENV=development pnpm test:itg

      - if: ${{ startsWith(github.ref, 'refs/heads/main') }}
        run: |
          pnpm install --frozen-lockfile
          NODE_ENV=production pnpm test:itg

  app_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - if: ${{ startsWith(github.ref, 'refs/heads') && !startsWith(github.ref, 'refs/heads/main') }}
        run: |
          pnpm install --frozen-lockfile
          NODE_ENV=development pnpm build

      - if: ${{ startsWith(github.ref, 'refs/heads/main') }}
        run: |
          pnpm install --frozen-lockfile
          NODE_ENV=production pnpm build
